name: Android Build and Release

on:
  push:
    branches:
      - master  # Change to your main branch name

permissions:
  contents: write  # Add write permission for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17
          distribution: 'adopt'

      - name: Build and package Android app
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
        working-directory: ./  # Assuming gradlew is in the root directory

      - name: Get App VersionName
        id: get_version_name
        run: |
          echo "VERSION_NAME=$(grep 'versionName' app/build.gradle | sed -n 's/.*"\(.*\)".*/\1/p')" >> $GITHUB_ENV
        shell: bash
