name: Build and Release Android

on:
  push:
    branches:
      - master  # Change this to your main branch if different

permissions:
  contents: write  # Provide write permission for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build and package the Android app
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Verify generated APK
        run: |
          if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
            echo "APK not found!"
            exit 1
          fi

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/BoatMap.apk

      - name: Get app version
        id: get_version_name
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle | sed -n 's/.*"\(.*\)".*/\1/p')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Create tag and GitHub release via API
        id: create_tag_and_release
        run: |
          TAG_NAME="v${{ env.VERSION_NAME }}"
          RELEASE_NAME="Release ${{ env.VERSION_NAME }}"
          REQUEST_BODY=$(jq -n --arg tag_name "$TAG_NAME" --arg target_commitish "$GITHUB_SHA" --arg name "$RELEASE_NAME" --arg body "Automated release for version $TAG_NAME" '{ tag_name: $tag_name, target_commitish: $target_commitish, name: $name, body: $body, draft: false, prerelease: false }')
          RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.BOATMAP_TOKEN }}" -H "Content-Type: application/json" -d "$REQUEST_BODY" "https://api.github.com/repos/${{ github.repository }}/releases")
          UPLOAD_URL=$(echo "$RESPONSE" | jq -r .upload_url | sed -e "s/{?name,label}//")
          if [ "$UPLOAD_URL" == "null" ]; then
            echo "Failed to get upload URL"
            exit 1
          fi
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.BOATMAP_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path:  app/build/outputs/apk/release/BoatMap.apk
