name: Android Build and Release

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Verify Gradle Wrapper
      run: |
        chmod +x ./gradlew
      working-directory: ./app  # Change to your app's directory

    - name: Build and package Android app
      run: |
        ./gradlew assembleRelease
      working-directory: ./app  # Change to your app's directory

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk  # Update with your build artifacts location
        token: ${{ secrets.BOATMAPTOKEN }}

    - name: Upload Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/*.apk  # Update with your build artifacts location
        asset_name: Boatmap-Release.apk  # Change the name as needed
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.BOATMAPTOKEN }}
